# Generated by Django 4.2.3 on 2024-07-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriculas',
            new_name='Matricula',
        ),
    ]
